language: node_js
rust:
  - stable
node_js:
  - node
os:
  - windows
#  - osx
#  - linux

env:
  - RUST_BACKTRACE=1

addons:
  apt:
    packages:
      - libwebkit2gtk-4.0-dev
      - libglib2.0-*
      - libssl-dev
      - libgtk-3-dev
      - libappindicator3-dev
      - patchelf
      - librsvg2-dev
      - libvips-dev

install:
  - choco
  - choco uninstall visualstudio2017-installer visualstudio2017-workload-netcorebuildtools visualstudio2017-workload-vctools visualstudio2017-workload-webbuildtools visualstudio2017buildtools
  - choco install -y rust wsl;
  - choco install visualstudio2019community visualstudio2019-workload-nativecrossplat visualstudio2019-workload-nativedesktop

#jobs:
#  include:
#    - language: rust
#      rust: stable

script:
  - yarn install --frozen-lockfile
  - yarn run tauri build
  
